library(plotly)
library(dplyr)
library(TSstudio)
install.packages("TSstudio")
library(TSstudio)
covid_data<-read.csv("WHO-COVID-19-global-data.csv")
View(covid_data)
covid_data$ï..Date_reported<-as.Date(covid_data$ï..Date_reported)
ts_plot(covid_data, line.mode = "lines+markers")
